frontend:
	bash components/frontend.sh

catalogue:
	bash components/catalogue.sh

cart:
	bash components/cart.sh

mongodb:
	bash components/mongodb.sh

redis:
	bash components/redis.sh

user:
	bash components/user.sh

mysql:
	bash components/mysql.sh

shipping:
	bash components/shipping.sh

rabbitmq:
	bash components/rabbitmq.sh

payment:
	bash components/payment.sh